version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:3.1.17
    container_name: tomcat8_resurface
    ports:
      - '7700:7700'
      - '7701:7701'


  tomcat8:
    image: test-tomcat8
    container_name: tomcat8
    ports:
      - '80:8080'
    env_file:
      - .env
